-- AI Resume Forge 分库初始化入口说明
-- 微服务已按业务库拆分，请分别执行同目录下的脚本：
--
-- 1. auth_schema.sql      -> ai_resume_auth
-- 2. resume_schema.sql    -> ai_resume_resume
-- 3. agent_schema.sql     -> ai_resume_agent
-- 4. interview_schema.sql -> ai_resume_interview
-- 5. order_schema.sql     -> ai_resume_order
--
-- 注意：微服务库之间不再创建跨库外键，只保留业务 ID 和索引。
-- 如果服务启用 Seata AT，每个业务库都需要自己的 undo_log 表。
